### ISSUE TITLE
Repeated Buttons

### ISSUE THREAD

**Issue by dedarritchon** [adamalston/v2#6]
Not really an Issue but you should remove the **Buttons** component in Content.js as it is also imported on App.js.

Also, Great Stuff! I love the minimal design and the interactive background.
I managed to deploy it on github pages following [this](https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f) tutorial.

I'll try adding a footer or smth to reference you as the author, you should definitely add one to the template.

Thanks for the awesome work!

**Comment by adamalston** [comment]
Thanks for reminding me, I have a bunch of changes that I havent pushed yet:

- [x] Removed `Buttons` from `Content.js` and adjusted the `scss` to account for that
- [x] Rewrote mobile `scss` for 4.7 inch displays (iPhone 6/7/8) up to 6.5 inch displays (iPhone 11 Pro Max and most Galaxy devices)
- [x] Reconfigured the toggle settings for different browsers 

I will probably push in the next few days as I finish up testing the toggle settings.

The footer is a good idea, thanks for the feedback!
